planplane/flights/urls.py
from django.urls import path

from . import views

app_name = 'flights'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('code<code_model>/', views.model_aircrafts, name='code'),
    path('airport/', views.airports_of_city, name='airports'),
    path('search/', views.ticket_search, name='ticket'),
    path('', views.main_page, name='mainPage'),
]

planplane/planplane/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('flights.urls')),
    path('admin/', admin.site.urls),
]

planplane/flights/models.py
from django.db import models
import json

class AircraftsData(models.Model):
    aircraft_code = models.CharField(primary_key=True, max_length=3)
    model = models.JSONField()
    range = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'aircrafts_data'

    def __str__(self):
        return self.model.get('en')


class AirportsData(models.Model):
    airport_code = models.CharField(primary_key=True, max_length=3)
    airport_name = models.JSONField()
    city = models.JSONField()
    coordinates = models.TextField()  # This field type is a guess.
    timezone = models.TextField()

    class Meta:
        managed = False
        db_table = 'airports_data'
    
    def __str__(self):
        return self.airport_code


class BoardingPasses(models.Model):
    ticket_no = models.OneToOneField('TicketFlights', models.DO_NOTHING, db_column='ticket_no', primary_key=True)
    flight_id = models.IntegerField()
    boarding_no = models.IntegerField()
    seat_no = models.CharField(max_length=4)

    class Meta:
        managed = False
        db_table = 'boarding_passes'
        unique_together = (('flight_id', 'boarding_no'), ('flight_id', 'seat_no'), ('ticket_no', 'flight_id'),)


class Bookings(models.Model):
    book_ref = models.CharField(primary_key=True, max_length=6)
    book_date = models.DateTimeField()
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = False
        db_table = 'bookings'


class Flights(models.Model):
    flight_id = models.AutoField(primary_key=True)
    flight_no = models.CharField(max_length=6)
    scheduled_departure = models.DateTimeField()
    scheduled_arrival = models.DateTimeField()
    departure_airport = models.ForeignKey(AirportsData, models.DO_NOTHING, db_column='departure_airport', related_name = 'departure_airport')
    arrival_airport = models.ForeignKey(AirportsData, models.DO_NOTHING, db_column='arrival_airport', related_name='arrival_airport')
    status = models.CharField(max_length=20)
    aircraft_code = models.ForeignKey(AircraftsData, models.DO_NOTHING, db_column='aircraft_code')
    actual_departure = models.DateTimeField(blank=True, null=True)
    actual_arrival = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'flights'
        unique_together = (('flight_no', 'scheduled_departure'),)


class Seats(models.Model):
    aircraft_code = models.OneToOneField(AircraftsData, models.DO_NOTHING, db_column='aircraft_code', primary_key=True)
    seat_no = models.CharField(max_length=4)
    fare_conditions = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'seats'
        unique_together = (('aircraft_code', 'seat_no'),)


class TicketFlights(models.Model):
    ticket_no = models.OneToOneField('Tickets', models.DO_NOTHING, db_column='ticket_no', primary_key=True)
    flight = models.ForeignKey(Flights, models.DO_NOTHING)
    fare_conditions = models.CharField(max_length=10)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        managed = False
        db_table = 'ticket_flights'
        unique_together = (('ticket_no', 'flight'),)


class Tickets(models.Model):
    ticket_no = models.CharField(primary_key=True, max_length=13)
    book_ref = models.ForeignKey(Bookings, models.DO_NOTHING, db_column='book_ref')
    passenger_id = models.CharField(max_length=20)
    passenger_name = models.TextField()
    contact_data = models.JSONField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tickets'

planplane/flights/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import *
from .localfunc import *

def index(request):
    temp = AircraftsData.objects.values('aircraft_code', 'model')
    context = { 'temp': temp}
    template = 'flights/index.html'
    return render(request, template, context)

def model_aircrafts(request, code_model):
    return HttpResponse("Aircrafts code: %s." % code_model)

def airports_of_city(request):
    if request.POST:
        temp = AirportsData.objects.filter(city__en=request.POST['namecity'])
        context = {'AirportsData': temp}
    else:
        context = {}
    template = 'flights/airport_form.html'
    return render(request, template, context)

def ticket_search(request):
    template = 'flights/ticket.html'
    initialData = {'cityArrived': '', 'cityDeparture': '', 'minDate': getStringDay() , 'valueDate': ''}
    context = {'title': 'Покупка билетов', 'initialData': initialData,}
    if request.POST:
        initialData['cityDeparture'] = request.POST['cityDeparture']
        initialData['cityArrived'] = request.POST['cityArrived']
        initialData['valueDate'] = request.POST['dateDeparture']
        airportsOfDeparture = AirportsData.objects.filter(city__ru=request.POST['cityDeparture'])
        airportsOfArrived = AirportsData.objects.filter(city__ru=request.POST['cityArrived'])
        context['tableFlights'] = Flights.objects.filter(scheduled_departure__date=request.POST['dateDeparture']).filter(departure_airport__in=airportsOfDeparture).filter(arrival_airport__in=airportsOfArrived)
    print(context)
    return render(request, template, context)

def main_page(request):
    template = 'flights/mainPage.html'
    context = {'title': 'Главная страница'}
    return render(request, template, context)

planplane/flights/templates/flights/airport_form.html
<form action="{% url 'flights:airports' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Аэропорты города</h1></legend>
            <input type="text" name="namecity" placeholder="Name of city">
    </fieldset>
    <input type="submit" value="Search">
    {% if AirportsData %}
        <table>
            <tr class="">
                <th class="">Airport Code</th>
                <th class="">Airport Name</th>
                <th class="">Timezone</th>
            </tr>
            {% for city in AirportsData %}
            <tr class="">
                <th class="">{{ city.airport_code }}</th>
                <th class="">{{ city.airport_name.en }}</th>
                <th class="">{{ city.timezone }}</th>
            </tr> 
            {% endfor%}
        </table>
    {% endif %}
</form>

planplane/flights/templates/flights/baseTemp/base.html
<!DOCTYPE html>
<html>
  <head>
      <title>
        {% block title %}
          {% if title %}
            {{ title }}
          {% else %}
            Base title
          {% endif %}
        {% endblock %}
      </title>
    <link rel="icon" href="../../../static/images/icon.png">
    <link href="../../../static/css/style.css" rel="stylesheet" />
  </head>
  <body>
    <div class="main">
      {% block header%}
        {% include "./header_temp.html"%}
      {% endblock %}
      {% block menu %}
        {% include "./menu_temp.html" %}
      {% endblock %}
      <div class="frame">
        {% block content %}
        {% endblock %}
      </div>
      {% block footer %}
        {% include "./footer_temp.html"%}
      {% endblock %}
    </div>
  </body>
</html>

planplane/flights/templates/flights/baseTemp/footer_temp.html
<div class="footer">
    <div class="leftf">
      <p class="foottext"><a href="">Служба поддержки</a></p>
      <p class="foottext"><a href="">Возврат билетов</a></p>
      <p class="foottext"><a href="">Предложения</a></p>
    </div>
    <div class="rightf">
      <p class="foottext"><a href="" class="">+0 (123) 456-78-90</a></p>
      <p class="foottext"><a href="" class="">pplane@fly.air</a></p>
      <p class="foottext"><a href="" class="">обл. Печальная, р-н Тоскливый, г. Грусть, пр-кт Разочарование, д. 13</a></p>
    </div>
</div>

planplane/flights/templates/flights/baseTemp/header_temp.html
<div class="header">
    <h1><a href="{% url 'flights:mainPage' %}">Plan Plane</a></h1>
    <a href="{% url 'flights:mainPage' %}"><img class="logo" src="../../static/images/Logo.png" alt="Logo"></a>
</div>

planplane/flights/templates/flights/baseTemp/menu_temp.html
<div class="navbar">
    <ul class="menu">
      <li class="menutable"><a href="{% url 'flights:ticket' %}">Поиск рейса</a></li>
      <li class="menutable indev"><a href="">Регистрация</a></li>
      <li class="menutable indev"><a href="">Вход</a></li>
      <!-- <li class="menutable indev"><a href="">О сайте</a></li> -->
      <li class="menutable"><a href="{% url 'flights:index' %}">О Сайте</a></li>
    </ul>
</div>

planplane/flights/templates/flights/index.html
<a href="{% url 'flights:airports' %}">Аэропорты</a>
<a href="{% url 'flights:ticket' %}">Билеты</a>

{% if temp %}
    <ul>
    {% for plane in temp %}
    {{ plane }}
        <li><a href="{% url 'flights:code' plane.aircraft_code %}">{{ plane.model.en }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Нет кодов???</p>
{% endif %}

planplane/flights/templates/flights/mainPage.html
{% extends "./baseTemp/base.html"%}

planplane/flights/templates/flights/ticket.html
{% extends "./baseTemp/base.html" %}
{% block content %}
<div class="tabletick">
    <div class="searchdiv">
      <form class="searchTicket" method="POST" action="{% url 'flights:ticket' %}">
        {% csrf_token %}
        <input class="nameCity departure" type="text" name="cityDeparture" placeholder="{% if initialData.cityDeparture %}{{initialData.cityDeparture}}{% else %}{{ 'Город отправления' }}{% endif %}" pattern="[A-Za-zА-Яа-яЁё]+[\s\-]?[A-Za-zА-Яа-яЁё]+[\s\-]?[A-Za-zА-Яа-яЁё]+" required>
        <img class="iconPlane" src="../../static/images/arrivedToDepartureSmall.png">
        <input class="nameCity arrived" type="text" name="cityArrived"  placeholder="{% if initialData.cityArrived %}{{initialData.cityArrived}}{% else %}{{ 'Город прибытия' }}{% endif %}" pattern="[A-Za-zА-Яа-яЁё]+[\s\-]?[A-Za-zА-Яа-яЁё]+[\s\-]?[A-Za-zА-Яа-яЁё]+" required>
        <input class="dateDeparture" type="date" name="dateDeparture" value="{% if initialData.valueDate %}{{initialData.valueDate}}{% else %}{{ initialData.minDate }}{% endif %}" required min="{{ initialData.minDate }}">
        <input class="submitTicket" type="submit" value="Поиск">
      </form>
    </div>
    <div class="tableover">
        {% if tableFlights %}
            {% for everyFlight in tableFlights %}
                <div class="infFlight baseBorder">
                    <div class="flight">
                        <div class="point center">
                            <p>{{ everyFlight.scheduled_departure | time:" H:i" }}</p>
                            <p>{{ everyFlight.scheduled_departure | date:"d.m" }}</p>
                            <p>{{ initialData.cityDeparture }}</p>
                            <p>{{ everyFlight.departure_airport }}</p>
                        </div>
                        <div class="timeAndIcon center">
                            <p>02:40</p>
                            <img class="iconPlane" src="../../static/images/arrivedToDepartureBaseSmall.png">
                        </div>
                        <div class="point center">
                            <p>{{ everyFlight.scheduled_arrival | time:" H:i" }}</p>
                            <p>{{ everyFlight.scheduled_arrival | date:"d.m" }}</p>
                            <p>{{ initialData.cityArrived }}</p>
                            <p>{{ everyFlight.arrival_airport }}</p>
                        </div>
                        <div class="costAndPlace center">
                            <p>Эконом: 56</p>
                            <p>Бизнес: 19</p>
                            <p>Цена: 6500 р.</p>
                            <button class="indev">Купить</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="infFlight baseBorder">
                <div class="flight center message">
                    <p>Введите название города вылета и города прилёта</p>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}